nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@resume/plugin-load-env.cjs
    spec: plugins/yarn-plugin-load-env/bundles/@resume/plugin-load-env.js

yarnPath: .yarn/releases/yarn-3.3.1.cjs
